init:
  - git config --global core.autocrlf true
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
build_script:
  - build.cmd --quiet verify
version: 1.0.0-beta2-build{build}
artifacts:
  - path: 'artifacts\build\**\*.nupkg'

clone_depth: 1
test: off
deploy: off